language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly # ignore errors, see below
  - hhvm # ignore errors, see below

# lock distro so new future defaults will not break the build
dist: trusty

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer install

before_script:
  - composer require phpunit/phpunit squizlabs/php_codesniffer

script:
  - php vendor/bin/phpunit
  - php vendor/bin/phpcs

after_script:
  - if [ -f ./build/logs/clover.xml ]; then travis_retry composer require php-coveralls/php-coveralls --no-interaction --update-with-dependencies; fi
  - if [ -f ./build/logs/clover.xml ]; then php vendor/bin/php-coveralls -v; fi
