dist: trusty
sudo: false

language: php

git:
  depth: 3

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
  include:
    - php: 5.0
    - php: 5.1
    - php: 5.2
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm
    - php: nightly

script:
  - php test.php
